// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/optimism/config/config.proto

package module

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types "github.com/datachainlab/ethereum-ibc-relay-prover/light-clients/ethereum/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	TrustingPeriod        time.Duration   `protobuf:"bytes,1,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	MaxClockDrift         time.Duration   `protobuf:"bytes,2,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	RefreshThresholdRate  *types.Fraction `protobuf:"bytes,3,opt,name=refresh_threshold_rate,json=refreshThresholdRate,proto3" json:"refresh_threshold_rate,omitempty"`
	OpNodeEndpoint        string          `protobuf:"bytes,4,opt,name=op_node_endpoint,json=opNodeEndpoint,proto3" json:"op_node_endpoint,omitempty"`
	L1ExecutionEndpoint   string          `protobuf:"bytes,5,opt,name=l1_execution_endpoint,json=l1ExecutionEndpoint,proto3" json:"l1_execution_endpoint,omitempty"`
	L1BeaconEndpoint      string          `protobuf:"bytes,6,opt,name=l1_beacon_endpoint,json=l1BeaconEndpoint,proto3" json:"l1_beacon_endpoint,omitempty"`
	PreimageMakerEndpoint string          `protobuf:"bytes,7,opt,name=preimage_maker_endpoint,json=preimageMakerEndpoint,proto3" json:"preimage_maker_endpoint,omitempty"`
	PreimageMakerTimeout  time.Duration   `protobuf:"bytes,8,opt,name=preimage_maker_timeout,json=preimageMakerTimeout,proto3,stdduration" json:"preimage_maker_timeout"`
	L1L2DistanceThreshold uint64          `protobuf:"varint,9,opt,name=l1_l2_distance_threshold,json=l1L2DistanceThreshold,proto3" json:"l1_l2_distance_threshold,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0efbec042dcf5e8, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func (m *ProverConfig) GetTrustingPeriod() time.Duration {
	if m != nil {
		return m.TrustingPeriod
	}
	return 0
}

func (m *ProverConfig) GetMaxClockDrift() time.Duration {
	if m != nil {
		return m.MaxClockDrift
	}
	return 0
}

func (m *ProverConfig) GetRefreshThresholdRate() *types.Fraction {
	if m != nil {
		return m.RefreshThresholdRate
	}
	return nil
}

func (m *ProverConfig) GetOpNodeEndpoint() string {
	if m != nil {
		return m.OpNodeEndpoint
	}
	return ""
}

func (m *ProverConfig) GetL1ExecutionEndpoint() string {
	if m != nil {
		return m.L1ExecutionEndpoint
	}
	return ""
}

func (m *ProverConfig) GetL1BeaconEndpoint() string {
	if m != nil {
		return m.L1BeaconEndpoint
	}
	return ""
}

func (m *ProverConfig) GetPreimageMakerEndpoint() string {
	if m != nil {
		return m.PreimageMakerEndpoint
	}
	return ""
}

func (m *ProverConfig) GetPreimageMakerTimeout() time.Duration {
	if m != nil {
		return m.PreimageMakerTimeout
	}
	return 0
}

func (m *ProverConfig) GetL1L2DistanceThreshold() uint64 {
	if m != nil {
		return m.L1L2DistanceThreshold
	}
	return 0
}

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.optimism.config.ProverConfig")
}

func init() {
	proto.RegisterFile("relayer/provers/optimism/config/config.proto", fileDescriptor_a0efbec042dcf5e8)
}

var fileDescriptor_a0efbec042dcf5e8 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xe3, 0xef, 0x2b, 0xa5, 0x35, 0xd0, 0x56, 0xa6, 0x29, 0xa6, 0x0b, 0x27, 0x62, 0x81,
	0x22, 0xd1, 0xcc, 0xc8, 0x41, 0x02, 0xd6, 0x69, 0xca, 0x86, 0x82, 0x2a, 0xab, 0x1b, 0x10, 0xd2,
	0x68, 0x3c, 0xbe, 0xb1, 0x47, 0x1d, 0x7b, 0xac, 0xf1, 0x38, 0x0a, 0x6f, 0xc1, 0x92, 0x47, 0xea,
	0xb2, 0x4b, 0x56, 0x14, 0x25, 0x2f, 0x82, 0x3c, 0xfe, 0x93, 0xc2, 0xaa, 0xab, 0x99, 0xcc, 0x39,
	0xbf, 0x73, 0xa2, 0x6b, 0x5d, 0xfb, 0x44, 0x81, 0xa0, 0xdf, 0x40, 0xe1, 0x5c, 0xc9, 0x05, 0xa8,
	0x02, 0xcb, 0x5c, 0xf3, 0x94, 0x17, 0x29, 0x66, 0x32, 0x9b, 0xf3, 0xb8, 0x39, 0x50, 0xae, 0xa4,
	0x96, 0xce, 0xa0, 0x71, 0xa3, 0xc6, 0x8d, 0x5a, 0x37, 0xaa, 0x6d, 0xc7, 0xaf, 0x78, 0xc8, 0xb0,
	0xe0, 0x71, 0xa2, 0x99, 0xe0, 0x90, 0xe9, 0x02, 0x83, 0x4e, 0x40, 0x41, 0x99, 0xe2, 0x85, 0xdf,
	0xdd, 0xeb, 0xb4, 0x63, 0x2f, 0x96, 0x32, 0x16, 0x80, 0xcd, 0xaf, 0xb0, 0x9c, 0xe3, 0xa8, 0x54,
	0x54, 0x73, 0x99, 0x35, 0xfa, 0x61, 0x2c, 0x63, 0x69, 0xae, 0xb8, 0xba, 0xd5, 0xaf, 0x2f, 0x6e,
	0xb7, 0xec, 0xc7, 0x17, 0xa6, 0xfe, 0xd4, 0x74, 0x3a, 0xe7, 0xf6, 0xbe, 0x56, 0x65, 0xa1, 0x79,
	0x16, 0x93, 0x1c, 0x14, 0x97, 0x91, 0x6b, 0x0d, 0xad, 0xd1, 0xa3, 0xc9, 0x73, 0x54, 0x17, 0xa0,
	0xb6, 0x00, 0xcd, 0x9a, 0x82, 0xe9, 0xce, 0xf5, 0xaf, 0x41, 0xef, 0xc7, 0xed, 0xc0, 0x0a, 0xf6,
	0x5a, 0xf6, 0xc2, 0xa0, 0xce, 0x07, 0x7b, 0x3f, 0xa5, 0x4b, 0xc2, 0x84, 0x64, 0x57, 0x24, 0x52,
	0x7c, 0xae, 0xdd, 0xff, 0xee, 0x9f, 0xf6, 0x24, 0xa5, 0xcb, 0xd3, 0x0a, 0x9d, 0x55, 0xa4, 0xf3,
	0xd5, 0x3e, 0x52, 0x30, 0x57, 0x50, 0x24, 0x44, 0x27, 0xd5, 0x21, 0x45, 0x44, 0x14, 0xd5, 0xe0,
	0xfe, 0x6f, 0x32, 0x5f, 0x22, 0x1e, 0x32, 0x74, 0x77, 0x5e, 0xa8, 0x9b, 0xd1, 0xc2, 0x47, 0xef,
	0x15, 0x65, 0x55, 0x41, 0x70, 0xd8, 0xa4, 0x5c, 0xb6, 0x21, 0x01, 0xd5, 0xe0, 0x8c, 0xec, 0x03,
	0x99, 0x93, 0x4c, 0x46, 0x40, 0x20, 0x8b, 0x72, 0xc9, 0x33, 0xed, 0x6e, 0x0d, 0xad, 0xd1, 0x6e,
	0xb0, 0x27, 0xf3, 0x4f, 0x32, 0x82, 0xb3, 0xe6, 0xd5, 0x99, 0xd8, 0x7d, 0xe1, 0x13, 0x58, 0x02,
	0x2b, 0xab, 0xbc, 0x8d, 0xfd, 0x81, 0xb1, 0x3f, 0x15, 0xfe, 0x59, 0xab, 0x75, 0xcc, 0x89, 0xed,
	0x08, 0x9f, 0x84, 0x40, 0xd9, 0x5d, 0x60, 0xdb, 0x00, 0x07, 0xc2, 0x9f, 0x1a, 0xa1, 0x73, 0xbf,
	0xb1, 0x9f, 0xe5, 0x0a, 0x78, 0x4a, 0x63, 0x20, 0x29, 0xbd, 0x02, 0xb5, 0x41, 0x1e, 0x1a, 0xa4,
	0xdf, 0xca, 0x1f, 0x2b, 0xb5, 0xe3, 0x3e, 0xdb, 0x47, 0xff, 0x70, 0x9a, 0xa7, 0x20, 0x4b, 0xed,
	0xee, 0xdc, 0x7f, 0xea, 0x87, 0x7f, 0x65, 0x5f, 0xd6, 0x01, 0xce, 0x5b, 0xdb, 0x15, 0x3e, 0x11,
	0x13, 0x12, 0xf1, 0x42, 0xd3, 0x8c, 0xc1, 0xe6, 0x1b, 0xb8, 0xbb, 0x43, 0x6b, 0xb4, 0x15, 0xf4,
	0x85, 0x7f, 0x3e, 0x99, 0x35, 0x6a, 0x37, 0xdb, 0x69, 0x70, 0xbd, 0xf2, 0xac, 0x9b, 0x95, 0x67,
	0xfd, 0x5e, 0x79, 0xd6, 0xf7, 0xb5, 0xd7, 0xbb, 0x59, 0x7b, 0xbd, 0x9f, 0x6b, 0xaf, 0xf7, 0xe5,
	0x5d, 0xcc, 0x75, 0x52, 0x86, 0x88, 0xc9, 0x14, 0x47, 0x54, 0x53, 0x96, 0x50, 0x9e, 0x09, 0x1a,
	0x76, 0x5b, 0x33, 0xe6, 0x21, 0x1b, 0x9b, 0x25, 0x19, 0xd7, 0x2b, 0x82, 0x53, 0x19, 0x95, 0x02,
	0xc2, 0x6d, 0xf3, 0xff, 0x5f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xee, 0x9f, 0x47, 0x70,
	0x03, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.L1L2DistanceThreshold != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.L1L2DistanceThreshold))
		i--
		dAtA[i] = 0x48
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.PreimageMakerTimeout, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PreimageMakerTimeout):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintConfig(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x42
	if len(m.PreimageMakerEndpoint) > 0 {
		i -= len(m.PreimageMakerEndpoint)
		copy(dAtA[i:], m.PreimageMakerEndpoint)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.PreimageMakerEndpoint)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.L1BeaconEndpoint) > 0 {
		i -= len(m.L1BeaconEndpoint)
		copy(dAtA[i:], m.L1BeaconEndpoint)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.L1BeaconEndpoint)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.L1ExecutionEndpoint) > 0 {
		i -= len(m.L1ExecutionEndpoint)
		copy(dAtA[i:], m.L1ExecutionEndpoint)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.L1ExecutionEndpoint)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OpNodeEndpoint) > 0 {
		i -= len(m.OpNodeEndpoint)
		copy(dAtA[i:], m.OpNodeEndpoint)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.OpNodeEndpoint)))
		i--
		dAtA[i] = 0x22
	}
	if m.RefreshThresholdRate != nil {
		{
			size, err := m.RefreshThresholdRate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxClockDrift, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintConfig(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintConfig(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovConfig(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift)
	n += 1 + l + sovConfig(uint64(l))
	if m.RefreshThresholdRate != nil {
		l = m.RefreshThresholdRate.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.OpNodeEndpoint)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.L1ExecutionEndpoint)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.L1BeaconEndpoint)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.PreimageMakerEndpoint)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PreimageMakerTimeout)
	n += 1 + l + sovConfig(uint64(l))
	if m.L1L2DistanceThreshold != 0 {
		n += 1 + sovConfig(uint64(m.L1L2DistanceThreshold))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDrift", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxClockDrift, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefreshThresholdRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RefreshThresholdRate == nil {
				m.RefreshThresholdRate = &types.Fraction{}
			}
			if err := m.RefreshThresholdRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpNodeEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OpNodeEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1ExecutionEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1ExecutionEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1BeaconEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1BeaconEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreimageMakerEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreimageMakerEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreimageMakerTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.PreimageMakerTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1L2DistanceThreshold", wireType)
			}
			m.L1L2DistanceThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L1L2DistanceThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
