// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/optimism/v1/optimism.proto

package module

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types1 "github.com/cosmos/ibc-go/v8/modules/core/02-client/types"
	types "github.com/datachainlab/ethereum-ibc-relay-prover/light-clients/ethereum/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type L1Config struct {
	GenesisValidatorsRoot        []byte                `protobuf:"bytes,1,opt,name=genesis_validators_root,json=genesisValidatorsRoot,proto3" json:"genesis_validators_root,omitempty"`
	MinSyncCommitteeParticipants uint64                `protobuf:"varint,2,opt,name=min_sync_committee_participants,json=minSyncCommitteeParticipants,proto3" json:"min_sync_committee_participants,omitempty"`
	GenesisTime                  uint64                `protobuf:"varint,3,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	ForkParameters               *types.ForkParameters `protobuf:"bytes,4,opt,name=fork_parameters,json=forkParameters,proto3" json:"fork_parameters,omitempty"`
	SecondsPerSlot               uint64                `protobuf:"varint,5,opt,name=seconds_per_slot,json=secondsPerSlot,proto3" json:"seconds_per_slot,omitempty"`
	SlotsPerEpoch                uint64                `protobuf:"varint,6,opt,name=slots_per_epoch,json=slotsPerEpoch,proto3" json:"slots_per_epoch,omitempty"`
	EpochsPerSyncCommitteePeriod uint64                `protobuf:"varint,7,opt,name=epochs_per_sync_committee_period,json=epochsPerSyncCommitteePeriod,proto3" json:"epochs_per_sync_committee_period,omitempty"`
	TrustLevel                   *types.Fraction       `protobuf:"bytes,8,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
}

func (m *L1Config) Reset()         { *m = L1Config{} }
func (m *L1Config) String() string { return proto.CompactTextString(m) }
func (*L1Config) ProtoMessage()    {}
func (*L1Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{0}
}
func (m *L1Config) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *L1Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_L1Config.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *L1Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L1Config.Merge(m, src)
}
func (m *L1Config) XXX_Size() int {
	return m.Size()
}
func (m *L1Config) XXX_DiscardUnknown() {
	xxx_messageInfo_L1Config.DiscardUnknown(m)
}

var xxx_messageInfo_L1Config proto.InternalMessageInfo

type ClientState struct {
	ChainId            uint64         `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IbcStoreAddress    []byte         `protobuf:"bytes,2,opt,name=ibc_store_address,json=ibcStoreAddress,proto3" json:"ibc_store_address,omitempty"`
	IbcCommitmentsSlot []byte         `protobuf:"bytes,3,opt,name=ibc_commitments_slot,json=ibcCommitmentsSlot,proto3" json:"ibc_commitments_slot,omitempty"`
	LatestHeight       *types1.Height `protobuf:"bytes,4,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	TrustingPeriod     time.Duration  `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	MaxClockDrift      time.Duration  `protobuf:"bytes,6,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	Frozen             bool           `protobuf:"varint,7,opt,name=frozen,proto3" json:"frozen,omitempty"`
	RollupConfigJson   []byte         `protobuf:"bytes,8,opt,name=rollup_config_json,json=rollupConfigJson,proto3" json:"rollup_config_json,omitempty"`
	L1Config           *L1Config      `protobuf:"bytes,9,opt,name=l1_config,json=l1Config,proto3" json:"l1_config,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{1}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type L1Header struct {
	TrustedSyncCommittee *types.TrustedSyncCommittee `protobuf:"bytes,1,opt,name=trusted_sync_committee,json=trustedSyncCommittee,proto3" json:"trusted_sync_committee,omitempty"`
	ConsensusUpdate      *types.ConsensusUpdate      `protobuf:"bytes,2,opt,name=consensus_update,json=consensusUpdate,proto3" json:"consensus_update,omitempty"`
	ExecutionUpdate      *types.ExecutionUpdate      `protobuf:"bytes,3,opt,name=execution_update,json=executionUpdate,proto3" json:"execution_update,omitempty"`
}

func (m *L1Header) Reset()         { *m = L1Header{} }
func (m *L1Header) String() string { return proto.CompactTextString(m) }
func (*L1Header) ProtoMessage()    {}
func (*L1Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{2}
}
func (m *L1Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *L1Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_L1Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *L1Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L1Header.Merge(m, src)
}
func (m *L1Header) XXX_Size() int {
	return m.Size()
}
func (m *L1Header) XXX_DiscardUnknown() {
	xxx_messageInfo_L1Header.DiscardUnknown(m)
}

var xxx_messageInfo_L1Header proto.InternalMessageInfo

type Derivation struct {
	AgreedL2HeadHash   []byte `protobuf:"bytes,2,opt,name=agreed_l2_head_hash,json=agreedL2HeadHash,proto3" json:"agreed_l2_head_hash,omitempty"`
	AgreedL2OutputRoot []byte `protobuf:"bytes,3,opt,name=agreed_l2_output_root,json=agreedL2OutputRoot,proto3" json:"agreed_l2_output_root,omitempty"`
	L2HeadHash         []byte `protobuf:"bytes,4,opt,name=l2_head_hash,json=l2HeadHash,proto3" json:"l2_head_hash,omitempty"`
	L2OutputRoot       []byte `protobuf:"bytes,5,opt,name=l2_output_root,json=l2OutputRoot,proto3" json:"l2_output_root,omitempty"`
	L2BlockNumber      uint64 `protobuf:"varint,6,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
}

func (m *Derivation) Reset()         { *m = Derivation{} }
func (m *Derivation) String() string { return proto.CompactTextString(m) }
func (*Derivation) ProtoMessage()    {}
func (*Derivation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{3}
}
func (m *Derivation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Derivation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Derivation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Derivation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Derivation.Merge(m, src)
}
func (m *Derivation) XXX_Size() int {
	return m.Size()
}
func (m *Derivation) XXX_DiscardUnknown() {
	xxx_messageInfo_Derivation.DiscardUnknown(m)
}

var xxx_messageInfo_Derivation proto.InternalMessageInfo

type Header struct {
	TrustedHeight *types1.Height       `protobuf:"bytes,1,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	AccountUpdate *types.AccountUpdate `protobuf:"bytes,2,opt,name=account_update,json=accountUpdate,proto3" json:"account_update,omitempty"`
	L1Head        *L1Header            `protobuf:"bytes,3,opt,name=l1_head,json=l1Head,proto3" json:"l1_head,omitempty"`
	Derivations   []*Derivation        `protobuf:"bytes,4,rep,name=derivations,proto3" json:"derivations,omitempty"`
	Preimages     []byte               `protobuf:"bytes,5,opt,name=preimages,proto3" json:"preimages,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{4}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return m.Size()
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

type ConsensusState struct {
	StorageRoot            []byte `protobuf:"bytes,1,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	Timestamp              uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OutputRoot             []byte `protobuf:"bytes,3,opt,name=output_root,json=outputRoot,proto3" json:"output_root,omitempty"`
	Hash                   []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	L1Slot                 uint64 `protobuf:"varint,5,opt,name=l1_slot,json=l1Slot,proto3" json:"l1_slot,omitempty"`
	L1CurrentSyncCommittee []byte `protobuf:"bytes,6,opt,name=l1_current_sync_committee,json=l1CurrentSyncCommittee,proto3" json:"l1_current_sync_committee,omitempty"`
	L1NextSyncCommittee    []byte `protobuf:"bytes,7,opt,name=l1_next_sync_committee,json=l1NextSyncCommittee,proto3" json:"l1_next_sync_committee,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{5}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type Misbehaviour struct {
	ClientId string  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Header_1 *Header `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2 *Header `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb29ee24a47cb9c, []int{6}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

func init() {
	proto.RegisterType((*L1Config)(nil), "ibc.lightclients.optimism.v1.L1Config")
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.optimism.v1.ClientState")
	proto.RegisterType((*L1Header)(nil), "ibc.lightclients.optimism.v1.L1Header")
	proto.RegisterType((*Derivation)(nil), "ibc.lightclients.optimism.v1.Derivation")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.optimism.v1.Header")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.optimism.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.optimism.v1.Misbehaviour")
}

func init() {
	proto.RegisterFile("ibc/lightclients/optimism/v1/optimism.proto", fileDescriptor_cbb29ee24a47cb9c)
}

var fileDescriptor_cbb29ee24a47cb9c = []byte{
	// 1186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdf, 0x6e, 0x13, 0xc7,
	0x17, 0x8e, 0x93, 0xe0, 0x38, 0x63, 0xc7, 0xce, 0x6f, 0x80, 0x60, 0xf8, 0x45, 0x4e, 0xb0, 0x10,
	0x8a, 0x0a, 0xb1, 0xbb, 0x46, 0xaa, 0xda, 0x2b, 0x04, 0x06, 0x0a, 0x34, 0xa5, 0xd1, 0x06, 0x50,
	0xd5, 0x9b, 0xd5, 0xec, 0xec, 0x89, 0x77, 0xca, 0xec, 0x8e, 0x35, 0x33, 0x6b, 0x85, 0xbe, 0x44,
	0x7b, 0xd9, 0x47, 0xe8, 0x4d, 0xdf, 0x03, 0xf5, 0x8a, 0xcb, 0x5e, 0xd1, 0x16, 0xa4, 0xde, 0xf5,
	0x1d, 0xaa, 0xf9, 0xb3, 0x8e, 0x9d, 0xb4, 0x81, 0xde, 0xcd, 0x9c, 0xf3, 0x7d, 0x67, 0xf6, 0x9c,
	0xef, 0x9c, 0x99, 0x45, 0x37, 0x58, 0x4c, 0xfb, 0x9c, 0x8d, 0x52, 0x4d, 0x39, 0x83, 0x5c, 0xab,
	0xbe, 0x18, 0x6b, 0x96, 0x31, 0x95, 0xf5, 0x27, 0xc1, 0x74, 0xdd, 0x1b, 0x4b, 0xa1, 0x05, 0xde,
	0x64, 0x31, 0xed, 0xcd, 0x82, 0x7b, 0x53, 0xc0, 0x24, 0xb8, 0x72, 0x61, 0x24, 0x46, 0xc2, 0x02,
	0xfb, 0x66, 0xe5, 0x38, 0x57, 0xb6, 0xcc, 0x01, 0x54, 0x48, 0xe8, 0x3b, 0x8e, 0x09, 0xeb, 0x56,
	0x1e, 0xd0, 0x19, 0x09, 0x31, 0xe2, 0xd0, 0xb7, 0xbb, 0xb8, 0x38, 0xec, 0x27, 0x85, 0x24, 0x9a,
	0x89, 0xdc, 0xfb, 0x4f, 0x7f, 0x21, 0xe8, 0x14, 0x24, 0x14, 0xf6, 0x0b, 0xcb, 0xb5, 0x03, 0x77,
	0xff, 0x5c, 0x42, 0xb5, 0xbd, 0x60, 0x28, 0xf2, 0x43, 0x36, 0xc2, 0x9f, 0xa0, 0x4b, 0x23, 0xc8,
	0x41, 0x31, 0x15, 0x4d, 0x08, 0x67, 0x09, 0xd1, 0x42, 0xaa, 0x48, 0x0a, 0xa1, 0xdb, 0x95, 0xed,
	0xca, 0x4e, 0x23, 0xbc, 0xe8, 0xdd, 0xcf, 0xa7, 0xde, 0x50, 0x08, 0x8d, 0xef, 0xa3, 0xad, 0x8c,
	0xe5, 0x91, 0x7a, 0x99, 0xd3, 0x88, 0x8a, 0x2c, 0x63, 0x5a, 0x03, 0x44, 0x63, 0x22, 0x35, 0xa3,
	0x6c, 0x4c, 0x72, 0xad, 0xda, 0x8b, 0xdb, 0x95, 0x9d, 0xe5, 0x70, 0x33, 0x63, 0xf9, 0xc1, 0xcb,
	0x9c, 0x0e, 0x4b, 0xd0, 0xfe, 0x0c, 0x06, 0x5f, 0x45, 0x8d, 0xf2, 0x78, 0xcd, 0x32, 0x68, 0x2f,
	0x59, 0x4e, 0xdd, 0xdb, 0x9e, 0xb2, 0x0c, 0xf0, 0x33, 0xd4, 0x3a, 0x14, 0xf2, 0x85, 0x89, 0x4d,
	0x32, 0xd0, 0x20, 0x55, 0x7b, 0x79, 0xbb, 0xb2, 0x53, 0x1f, 0xdc, 0xec, 0x9d, 0x2a, 0xf5, 0x34,
	0xd3, 0x49, 0xd0, 0x7b, 0x20, 0xe4, 0x8b, 0xfd, 0x29, 0x27, 0x6c, 0x1e, 0xce, 0xed, 0xf1, 0x0e,
	0x5a, 0x57, 0x40, 0x45, 0x9e, 0xa8, 0x68, 0x0c, 0x32, 0x52, 0x5c, 0xe8, 0xf6, 0x39, 0x7b, 0x7a,
	0xd3, 0xdb, 0xf7, 0x41, 0x1e, 0x70, 0xa1, 0xf1, 0x75, 0xd4, 0x32, 0x5e, 0x87, 0x83, 0xb1, 0xa0,
	0x69, 0xbb, 0x6a, 0x81, 0x6b, 0xd6, 0xbc, 0x0f, 0xf2, 0xbe, 0x31, 0xe2, 0x07, 0x68, 0xdb, 0x7a,
	0x7d, 0xc0, 0x13, 0x95, 0x01, 0xc9, 0x44, 0xd2, 0x5e, 0x71, 0x35, 0x71, 0x38, 0x73, 0xc0, 0x5c,
	0x65, 0x2c, 0x06, 0x7f, 0x8e, 0xea, 0x5a, 0x16, 0x4a, 0x47, 0x1c, 0x26, 0xc0, 0xdb, 0x35, 0x9b,
	0xec, 0xf5, 0xf7, 0x24, 0x2b, 0x09, 0x35, 0xfd, 0x10, 0x22, 0x4b, 0xdd, 0x33, 0xcc, 0xee, 0x5f,
	0x4b, 0xa8, 0x3e, 0xb4, 0xe0, 0x03, 0x4d, 0x34, 0xe0, 0xcb, 0xa8, 0x46, 0x53, 0xc2, 0xf2, 0x88,
	0x25, 0x56, 0xdc, 0xe5, 0x70, 0xc5, 0xee, 0x1f, 0x25, 0xf8, 0x23, 0xf4, 0x3f, 0x16, 0xd3, 0x48,
	0x69, 0x21, 0x21, 0x22, 0x49, 0x22, 0x41, 0x39, 0x01, 0x1b, 0x61, 0x8b, 0xc5, 0xf4, 0xc0, 0xd8,
	0xef, 0x38, 0x33, 0xfe, 0x18, 0x5d, 0x30, 0x58, 0x97, 0x5b, 0x66, 0x3e, 0xc5, 0x55, 0x6f, 0xc9,
	0xc2, 0x31, 0x8b, 0x7d, 0x46, 0xd6, 0x65, 0x2b, 0x78, 0x1b, 0xad, 0x71, 0xa2, 0x41, 0xe9, 0x28,
	0x05, 0x93, 0x81, 0x17, 0xf0, 0x8a, 0xcd, 0xc9, 0xf4, 0x7d, 0xcf, 0x77, 0xfb, 0x24, 0xe8, 0x3d,
	0xb4, 0x88, 0xb0, 0xe1, 0x08, 0x6e, 0x87, 0xf7, 0x50, 0xcb, 0xe6, 0xc5, 0xf2, 0x51, 0x59, 0xc9,
	0x73, 0x36, 0xc4, 0xe5, 0x9e, 0x9b, 0x8c, 0x5e, 0x39, 0x19, 0xbd, 0x7b, 0x7e, 0x32, 0xee, 0xd6,
	0x5e, 0xbd, 0xd9, 0x5a, 0xf8, 0xf1, 0xb7, 0xad, 0x4a, 0xd8, 0x2c, 0xb9, 0xbe, 0xc0, 0x5f, 0xa0,
	0x56, 0x46, 0x8e, 0x22, 0xca, 0x05, 0x7d, 0x11, 0x25, 0x92, 0x1d, 0x6a, 0x2b, 0xe8, 0x07, 0x46,
	0x5b, 0xcb, 0xc8, 0xd1, 0xd0, 0x50, 0xef, 0x19, 0x26, 0xde, 0x40, 0xd5, 0x43, 0x29, 0xbe, 0x83,
	0xdc, 0x6a, 0x5b, 0x0b, 0xfd, 0x0e, 0xdf, 0x44, 0x58, 0x0a, 0xce, 0x8b, 0x71, 0x44, 0xed, 0xa4,
	0x45, 0xdf, 0x2a, 0x91, 0x5b, 0x31, 0x1b, 0xe1, 0xba, 0xf3, 0xb8, 0x11, 0x7c, 0xac, 0x44, 0x8e,
	0x87, 0x68, 0x95, 0x07, 0x1e, 0xd9, 0x5e, 0xfd, 0x37, 0xc5, 0x67, 0x6e, 0x92, 0x5e, 0x39, 0xc1,
	0x61, 0x8d, 0xfb, 0x55, 0xf7, 0xa7, 0x45, 0x33, 0xd8, 0x0f, 0x81, 0x24, 0x20, 0x71, 0x8a, 0x36,
	0x6c, 0xda, 0x90, 0x9c, 0x68, 0x45, 0x2b, 0x7d, 0x7d, 0x30, 0x38, 0xbb, 0xa1, 0x9e, 0x3a, 0xee,
	0x5c, 0x7f, 0x86, 0x17, 0xf4, 0x3f, 0x58, 0xf1, 0xd7, 0x68, 0x9d, 0x8a, 0x5c, 0x41, 0xae, 0x0a,
	0x15, 0x15, 0xe3, 0x84, 0x68, 0xb0, 0xad, 0x53, 0x1f, 0xec, 0x9e, 0x7d, 0xc6, 0xb0, 0x64, 0x3d,
	0xb3, 0xa4, 0xb0, 0x45, 0xe7, 0x0d, 0x26, 0x32, 0x1c, 0x01, 0x2d, 0x8c, 0x02, 0x65, 0xe4, 0xa5,
	0x0f, 0x89, 0x7c, 0xbf, 0x64, 0x95, 0x91, 0x61, 0xde, 0xd0, 0x7d, 0x53, 0x41, 0xe8, 0x1e, 0x48,
	0x36, 0xb1, 0xea, 0xe2, 0x5d, 0x74, 0x9e, 0x8c, 0x24, 0x40, 0x12, 0xf1, 0x41, 0x94, 0x02, 0x49,
	0xa2, 0x94, 0xa8, 0xd4, 0x0f, 0xc0, 0xba, 0x73, 0xed, 0x0d, 0x4c, 0x65, 0x1f, 0x12, 0x95, 0xe2,
	0x00, 0x5d, 0x3c, 0x86, 0x8b, 0x42, 0x8f, 0x0b, 0xed, 0xae, 0x4c, 0x3f, 0x02, 0x25, 0xe1, 0x2b,
	0xeb, 0xb2, 0xf7, 0xe5, 0x36, 0x6a, 0xcc, 0x85, 0x5e, 0xb6, 0x48, 0xc4, 0x8f, 0x83, 0x5e, 0x43,
	0xcd, 0x13, 0xd1, 0xce, 0x59, 0x4c, 0x83, 0xcf, 0xc6, 0xb9, 0x8e, 0x5a, 0x7c, 0x10, 0xc5, 0xb6,
	0x75, 0xf3, 0x22, 0x8b, 0x41, 0x96, 0x97, 0x11, 0x1f, 0xdc, 0x35, 0xd6, 0x27, 0xd6, 0xd8, 0xfd,
	0x65, 0x11, 0x55, 0x7d, 0x27, 0xdc, 0x41, 0xcd, 0xb2, 0x13, 0xfc, 0xf8, 0x55, 0xde, 0x3b, 0x7e,
	0x6b, 0x9e, 0xe1, 0xe7, 0x2f, 0x44, 0x4d, 0x42, 0xa9, 0x28, 0x72, 0x3d, 0x2f, 0xf0, 0x8d, 0xb3,
	0x65, 0xb8, 0xe3, 0x38, 0x5e, 0x84, 0x35, 0x32, 0xbb, 0xc5, 0xb7, 0xd1, 0x0a, 0x0f, 0x6c, 0x45,
	0xbc, 0xa6, 0xef, 0x6d, 0x78, 0x97, 0x4f, 0x58, 0xe5, 0x76, 0x85, 0x1f, 0xa3, 0x7a, 0x32, 0x95,
	0xd0, 0x3c, 0x0a, 0x4b, 0x3b, 0xf5, 0xc1, 0xce, 0xd9, 0x41, 0x8e, 0x35, 0x0f, 0x67, 0xc9, 0x78,
	0x13, 0xad, 0x8e, 0x25, 0xb0, 0x8c, 0x8c, 0x40, 0xf9, 0xba, 0x1f, 0x1b, 0xba, 0xdf, 0x2f, 0xa2,
	0xe6, 0xb4, 0x59, 0xdd, 0x5d, 0x7a, 0x15, 0x35, 0xcc, 0x65, 0x49, 0x46, 0x30, 0xfb, 0x58, 0xd6,
	0xbd, 0xcd, 0x4a, 0xb5, 0x89, 0x56, 0xcd, 0x9b, 0xa6, 0x34, 0xc9, 0xc6, 0xfe, 0x31, 0x3c, 0x36,
	0xe0, 0x2d, 0x54, 0x3f, 0xdd, 0x39, 0x48, 0x1c, 0x2b, 0x8d, 0xd1, 0xf2, 0x4c, 0xa7, 0xd8, 0x35,
	0xbe, 0x64, 0x6b, 0x36, 0xf3, 0x56, 0x55, 0x79, 0x60, 0x6f, 0xd8, 0xcf, 0xd0, 0x65, 0x73, 0x7f,
	0x14, 0x52, 0x42, 0xae, 0x4f, 0x0e, 0x7c, 0xd5, 0x46, 0xd8, 0xe0, 0xc1, 0xd0, 0xf9, 0xe7, 0xc7,
	0xf7, 0x16, 0xda, 0xe0, 0x41, 0x94, 0xc3, 0xd1, 0x29, 0xde, 0x8a, 0xe5, 0x9d, 0xe7, 0xc1, 0x13,
	0x38, 0x9a, 0x27, 0x75, 0x7f, 0xae, 0xa0, 0xc6, 0x97, 0x4c, 0xc5, 0x90, 0x92, 0x09, 0x13, 0x85,
	0xc4, 0xff, 0x47, 0xab, 0xae, 0xde, 0xe5, 0xe3, 0xb2, 0x1a, 0xd6, 0x9c, 0xe1, 0x51, 0x82, 0x6f,
	0xa3, 0x5a, 0x6a, 0xb5, 0x8b, 0x02, 0xdf, 0x38, 0xd7, 0xce, 0x96, 0xc9, 0x2b, 0xbd, 0xe2, 0x58,
	0xc1, 0x4c, 0x80, 0x81, 0x6f, 0x96, 0xff, 0x14, 0x60, 0x70, 0xf7, 0xf9, 0xab, 0x3f, 0x3a, 0x0b,
	0xaf, 0xde, 0x76, 0x2a, 0xaf, 0xdf, 0x76, 0x2a, 0xbf, 0xbf, 0xed, 0x54, 0x7e, 0x78, 0xd7, 0x59,
	0x78, 0xfd, 0xae, 0xb3, 0xf0, 0xeb, 0xbb, 0xce, 0xc2, 0x37, 0x9f, 0x8e, 0x98, 0x4e, 0x8b, 0xb8,
	0x47, 0x45, 0xd6, 0x4f, 0x88, 0x26, 0xf6, 0x55, 0xe4, 0x24, 0x9e, 0xfe, 0xdb, 0xed, 0xb2, 0x98,
	0xee, 0x4a, 0xe0, 0xe4, 0xe5, 0xee, 0x58, 0x8a, 0x09, 0xc8, 0x7e, 0x26, 0x92, 0x82, 0x43, 0x5c,
	0xb5, 0x2f, 0xc5, 0xad, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x1f, 0xc0, 0x41, 0x23, 0x0a,
	0x00, 0x00,
}

func (m *L1Config) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *L1Config) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *L1Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TrustLevel != nil {
		{
			size, err := m.TrustLevel.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.EpochsPerSyncCommitteePeriod != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.EpochsPerSyncCommitteePeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.SlotsPerEpoch != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.SlotsPerEpoch))
		i--
		dAtA[i] = 0x30
	}
	if m.SecondsPerSlot != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.SecondsPerSlot))
		i--
		dAtA[i] = 0x28
	}
	if m.ForkParameters != nil {
		{
			size, err := m.ForkParameters.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.GenesisTime != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.GenesisTime))
		i--
		dAtA[i] = 0x18
	}
	if m.MinSyncCommitteeParticipants != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.MinSyncCommitteeParticipants))
		i--
		dAtA[i] = 0x10
	}
	if len(m.GenesisValidatorsRoot) > 0 {
		i -= len(m.GenesisValidatorsRoot)
		copy(dAtA[i:], m.GenesisValidatorsRoot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.GenesisValidatorsRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.L1Config != nil {
		{
			size, err := m.L1Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RollupConfigJson) > 0 {
		i -= len(m.RollupConfigJson)
		copy(dAtA[i:], m.RollupConfigJson)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.RollupConfigJson)))
		i--
		dAtA[i] = 0x42
	}
	if m.Frozen {
		i--
		if m.Frozen {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxClockDrift, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintOptimism(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x32
	n5, err5 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintOptimism(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x2a
	if m.LatestHeight != nil {
		{
			size, err := m.LatestHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.IbcCommitmentsSlot) > 0 {
		i -= len(m.IbcCommitmentsSlot)
		copy(dAtA[i:], m.IbcCommitmentsSlot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.IbcCommitmentsSlot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcStoreAddress) > 0 {
		i -= len(m.IbcStoreAddress)
		copy(dAtA[i:], m.IbcStoreAddress)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.IbcStoreAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChainId != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *L1Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *L1Header) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *L1Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExecutionUpdate != nil {
		{
			size, err := m.ExecutionUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ConsensusUpdate != nil {
		{
			size, err := m.ConsensusUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TrustedSyncCommittee != nil {
		{
			size, err := m.TrustedSyncCommittee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Derivation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Derivation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Derivation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.L2BlockNumber != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.L2BlockNumber))
		i--
		dAtA[i] = 0x30
	}
	if len(m.L2OutputRoot) > 0 {
		i -= len(m.L2OutputRoot)
		copy(dAtA[i:], m.L2OutputRoot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.L2OutputRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.L2HeadHash) > 0 {
		i -= len(m.L2HeadHash)
		copy(dAtA[i:], m.L2HeadHash)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.L2HeadHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AgreedL2OutputRoot) > 0 {
		i -= len(m.AgreedL2OutputRoot)
		copy(dAtA[i:], m.AgreedL2OutputRoot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.AgreedL2OutputRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AgreedL2HeadHash) > 0 {
		i -= len(m.AgreedL2HeadHash)
		copy(dAtA[i:], m.AgreedL2HeadHash)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.AgreedL2HeadHash)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Header) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Preimages) > 0 {
		i -= len(m.Preimages)
		copy(dAtA[i:], m.Preimages)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.Preimages)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Derivations) > 0 {
		for iNdEx := len(m.Derivations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Derivations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOptimism(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.L1Head != nil {
		{
			size, err := m.L1Head.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AccountUpdate != nil {
		{
			size, err := m.AccountUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TrustedHeight != nil {
		{
			size, err := m.TrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.L1NextSyncCommittee) > 0 {
		i -= len(m.L1NextSyncCommittee)
		copy(dAtA[i:], m.L1NextSyncCommittee)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.L1NextSyncCommittee)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.L1CurrentSyncCommittee) > 0 {
		i -= len(m.L1CurrentSyncCommittee)
		copy(dAtA[i:], m.L1CurrentSyncCommittee)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.L1CurrentSyncCommittee)))
		i--
		dAtA[i] = 0x32
	}
	if m.L1Slot != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.L1Slot))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OutputRoot) > 0 {
		i -= len(m.OutputRoot)
		copy(dAtA[i:], m.OutputRoot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.OutputRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Timestamp != 0 {
		i = encodeVarintOptimism(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StorageRoot) > 0 {
		i -= len(m.StorageRoot)
		copy(dAtA[i:], m.StorageRoot)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.StorageRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Header_2 != nil {
		{
			size, err := m.Header_2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Header_1 != nil {
		{
			size, err := m.Header_1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOptimism(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintOptimism(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOptimism(dAtA []byte, offset int, v uint64) int {
	offset -= sovOptimism(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *L1Config) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GenesisValidatorsRoot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.MinSyncCommitteeParticipants != 0 {
		n += 1 + sovOptimism(uint64(m.MinSyncCommitteeParticipants))
	}
	if m.GenesisTime != 0 {
		n += 1 + sovOptimism(uint64(m.GenesisTime))
	}
	if m.ForkParameters != nil {
		l = m.ForkParameters.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.SecondsPerSlot != 0 {
		n += 1 + sovOptimism(uint64(m.SecondsPerSlot))
	}
	if m.SlotsPerEpoch != 0 {
		n += 1 + sovOptimism(uint64(m.SlotsPerEpoch))
	}
	if m.EpochsPerSyncCommitteePeriod != 0 {
		n += 1 + sovOptimism(uint64(m.EpochsPerSyncCommitteePeriod))
	}
	if m.TrustLevel != nil {
		l = m.TrustLevel.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovOptimism(uint64(m.ChainId))
	}
	l = len(m.IbcStoreAddress)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.IbcCommitmentsSlot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.LatestHeight != nil {
		l = m.LatestHeight.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovOptimism(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift)
	n += 1 + l + sovOptimism(uint64(l))
	if m.Frozen {
		n += 2
	}
	l = len(m.RollupConfigJson)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.L1Config != nil {
		l = m.L1Config.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func (m *L1Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustedSyncCommittee != nil {
		l = m.TrustedSyncCommittee.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.ConsensusUpdate != nil {
		l = m.ConsensusUpdate.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.ExecutionUpdate != nil {
		l = m.ExecutionUpdate.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func (m *Derivation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgreedL2HeadHash)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.AgreedL2OutputRoot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.L2HeadHash)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.L2OutputRoot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.L2BlockNumber != 0 {
		n += 1 + sovOptimism(uint64(m.L2BlockNumber))
	}
	return n
}

func (m *Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustedHeight != nil {
		l = m.TrustedHeight.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.AccountUpdate != nil {
		l = m.AccountUpdate.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.L1Head != nil {
		l = m.L1Head.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if len(m.Derivations) > 0 {
		for _, e := range m.Derivations {
			l = e.Size()
			n += 1 + l + sovOptimism(uint64(l))
		}
	}
	l = len(m.Preimages)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StorageRoot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovOptimism(uint64(m.Timestamp))
	}
	l = len(m.OutputRoot)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.L1Slot != 0 {
		n += 1 + sovOptimism(uint64(m.L1Slot))
	}
	l = len(m.L1CurrentSyncCommittee)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	l = len(m.L1NextSyncCommittee)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func (m *Misbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.Header_1 != nil {
		l = m.Header_1.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	if m.Header_2 != nil {
		l = m.Header_2.Size()
		n += 1 + l + sovOptimism(uint64(l))
	}
	return n
}

func sovOptimism(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOptimism(x uint64) (n int) {
	return sovOptimism(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *L1Config) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: L1Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: L1Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisValidatorsRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisValidatorsRoot = append(m.GenesisValidatorsRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.GenesisValidatorsRoot == nil {
				m.GenesisValidatorsRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSyncCommitteeParticipants", wireType)
			}
			m.MinSyncCommitteeParticipants = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinSyncCommitteeParticipants |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTime", wireType)
			}
			m.GenesisTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForkParameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ForkParameters == nil {
				m.ForkParameters = &types.ForkParameters{}
			}
			if err := m.ForkParameters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondsPerSlot", wireType)
			}
			m.SecondsPerSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondsPerSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotsPerEpoch", wireType)
			}
			m.SlotsPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotsPerEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochsPerSyncCommitteePeriod", wireType)
			}
			m.EpochsPerSyncCommitteePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochsPerSyncCommitteePeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustLevel == nil {
				m.TrustLevel = &types.Fraction{}
			}
			if err := m.TrustLevel.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcStoreAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcStoreAddress = append(m.IbcStoreAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcStoreAddress == nil {
				m.IbcStoreAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcCommitmentsSlot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcCommitmentsSlot = append(m.IbcCommitmentsSlot[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcCommitmentsSlot == nil {
				m.IbcCommitmentsSlot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestHeight == nil {
				m.LatestHeight = &types1.Height{}
			}
			if err := m.LatestHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDrift", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxClockDrift, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frozen", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Frozen = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupConfigJson", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupConfigJson = append(m.RollupConfigJson[:0], dAtA[iNdEx:postIndex]...)
			if m.RollupConfigJson == nil {
				m.RollupConfigJson = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.L1Config == nil {
				m.L1Config = &L1Config{}
			}
			if err := m.L1Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *L1Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: L1Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: L1Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedSyncCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedSyncCommittee == nil {
				m.TrustedSyncCommittee = &types.TrustedSyncCommittee{}
			}
			if err := m.TrustedSyncCommittee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusUpdate == nil {
				m.ConsensusUpdate = &types.ConsensusUpdate{}
			}
			if err := m.ConsensusUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExecutionUpdate == nil {
				m.ExecutionUpdate = &types.ExecutionUpdate{}
			}
			if err := m.ExecutionUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Derivation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Derivation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Derivation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreedL2HeadHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgreedL2HeadHash = append(m.AgreedL2HeadHash[:0], dAtA[iNdEx:postIndex]...)
			if m.AgreedL2HeadHash == nil {
				m.AgreedL2HeadHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreedL2OutputRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgreedL2OutputRoot = append(m.AgreedL2OutputRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.AgreedL2OutputRoot == nil {
				m.AgreedL2OutputRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L2HeadHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L2HeadHash = append(m.L2HeadHash[:0], dAtA[iNdEx:postIndex]...)
			if m.L2HeadHash == nil {
				m.L2HeadHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L2OutputRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L2OutputRoot = append(m.L2OutputRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.L2OutputRoot == nil {
				m.L2OutputRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L2BlockNumber", wireType)
			}
			m.L2BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L2BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedHeight == nil {
				m.TrustedHeight = &types1.Height{}
			}
			if err := m.TrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountUpdate == nil {
				m.AccountUpdate = &types.AccountUpdate{}
			}
			if err := m.AccountUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.L1Head == nil {
				m.L1Head = &L1Header{}
			}
			if err := m.L1Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Derivations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Derivations = append(m.Derivations, &Derivation{})
			if err := m.Derivations[len(m.Derivations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Preimages", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Preimages = append(m.Preimages[:0], dAtA[iNdEx:postIndex]...)
			if m.Preimages == nil {
				m.Preimages = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageRoot = append(m.StorageRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StorageRoot == nil {
				m.StorageRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputRoot = append(m.OutputRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.OutputRoot == nil {
				m.OutputRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1Slot", wireType)
			}
			m.L1Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L1Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1CurrentSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1CurrentSyncCommittee = append(m.L1CurrentSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.L1CurrentSyncCommittee == nil {
				m.L1CurrentSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1NextSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1NextSyncCommittee = append(m.L1NextSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.L1NextSyncCommittee == nil {
				m.L1NextSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header_1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header_1 == nil {
				m.Header_1 = &Header{}
			}
			if err := m.Header_1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header_2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptimism
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptimism
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header_2 == nil {
				m.Header_2 = &Header{}
			}
			if err := m.Header_2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOptimism(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptimism
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOptimism(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOptimism
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptimism
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOptimism
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOptimism
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOptimism
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOptimism        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOptimism          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOptimism = fmt.Errorf("proto: unexpected end of group")
)
