name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Clean up unnecessary packages
        run: |
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/local/share/boost" || true
          docker system prune -a --volumes -f
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - name: Clean up unnecessary docker volumes
        run: |
          docker system prune -a --volumes -f
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'v1.0.0'
      - name: Install kurtosis
        run: |
          sudo apt-get install jq
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt remove kurtosis-cli
          sudo apt install kurtosis-cli=1.15.2 -V
      - name: Download optimism-devnet
        run: |
          git clone -b v1.4.2 https://github.com/datachainlab/optimism-devnet
      - name: Download optimism-preimage-maker
        run: |
          git clone -b feature/support_glamsterdam https://github.com/datachainlab/optimism-preimage-maker
      - name: Start optimism dev net
        run: |
          cd optimism-devnet
          OP_TAG=op-reth/v2.4.1 make chain
          GETH_VERSION=v1.17.3 LODESTAR_VERSION=v1.43.0 make devnet-up
      - name: Set port
        run: |
          cd optimism-preimage-maker
          make set-port
      - name: Deploy contracts
        run: |
          make set-port
          make contracts
        env:
          PREIMAGE_MAKER: ./
      - name: Start preimage server
        run: |
          cd optimism-preimage-maker
          make server-up &
          make wait
      - name: Clean up cache
        run: |
          sudo rm -rf $HOME/.cargo/registry
          sudo rm -rf $HOME/.cache
      - name: Test
        run: |
          sleep 180
          go test ./module/...
        env:
          PREIMAGE_MAKER: ./

